name: ttt CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  IMAGE_NAME: myapp:test

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Image (No Push on PR)
        uses: docker/build-push-action@v5
        with:
          context: ./ttt/v3.2
          push: false
          load: true
          tags: ${{ env.IMAGE_NAME }}

      - name: Make test script executable
        run: chmod +x ./scripts/run-tests.sh

      - name: Run Container Tests
        run: |
          ./scripts/run-tests.sh ${{ env.IMAGE_NAME }}

  push-image:
    if: github.event_name == 'push'
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          context: ./ttt/v3.2
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/myapp:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/myapp:latest
